model_type: auto
model_name_or_path: hllj/zephyr-7b-beta-vi-math
train_file_dir: datasets/finetune
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
do_train: true
do_eval: true
use_peft: true
fp16: true
model_max_length: 1024
num_train_epochs: 1
learning_rate: 2e-5
warmup_ratio: 0.05
weight_decay: 0.05
logging_strategy: steps
logging_steps: 10
eval_steps: 50
evaluation_strategy: steps
save_steps: 500
save_strategy: steps
save_total_limit: 13
gradient_accumulation_steps: 1
preprocessing_num_workers: 4
output_dir: outputs-sft-zephyr-beta-vi-math-v1
overwrite_output_dir: true
ddp_timeout: 30000
logging_first_step: true
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj

torch_dtype: float16
device_map: auto
report_to: tensorboard
ddp_find_unused_parameters: false
gradient_checkpointing: true
cache_dir: ./cache