project: zaloai_2023_math_solving
name: experiment-tracking-zaloai_2023_math_solving
wandb:
  WANDB_API_KEY: WANDB_API_KEY
  entity: yourname
  project: zaloai_2023_math_solving
  name: zaloai_2023_math_solving
  group: zaloai_2023_math_solving_training
  job_type: Finetuning
use_wandb: False
parameters:
  None: NaN
